56 subissue 92 adding a new time block to the curriculum
CSC207-2022F-UofT/course-project-schedulize pull request #62
Opened 2022-11-21 16:42 UTC by Amir1441

Just adding my use case of adding a new time block to the curriculum to the use case folder.

2022-11-22 00:50 UTC, od-obas1187 requested changes
One comment; correct me if I'm wrong, but I don't think the Controller should have access to the TimeBlock entity (or any entities at all) because of Clean Architecture's dependence structure. I'm pretty sure it should depend on the interactor.

2022-11-22 04:24 UTC, Amir1441 commented
> One comment; correct me if I'm wrong, but I don't think the Controller should have access to the TimeBlock entity (or any entities at all) because of Clean Architecture's dependence structure. I'm pretty sure it should depend on the interactor.

You're completely right. I'll make the changes. This pull request was just supposed to add the files to the main

2022-11-24 06:04 UTC, Bhan-Aayush commented
I see you have taken Odosa's comment and changed it, and your interaction looks fine. Next time you can also add comments in the description of the code.

2022-11-24 06:05 UTC, Bhan-Aayush approved these changes

2022-11-26 16:51 UTC, bmguiler approved these changes

2022-11-29 15:30 UTC, closed without merging