Implemented CommonTimeBlock
CSC207-2022F-UofT/course-project-schedulize pull request #68
Opened 2022-11-23 20:26 UTC by MMachadoUofT

I definitely see why TDD is so highly regarded... lots of tiny bugs I wouldn't have been able to find otherwise. I made sure to include thorough tests to assure that this suite was as penetrative as possible. The rest of the remaining classes are very simple, as they are basically just containers for the ones I've created thus far, and any of their functionality will primarily involve calling their sub-entities' methods.

2022-11-24 00:24 UTC, Amir1441 submitted a review, later dismissed

2022-11-24 00:57 UTC, Eggathin submitted a review, later dismissed

2022-11-24 15:13 UTC, dadler83 requested changes
If the tests all pass, it looks pretty good. I left some minor comments about cleaning up the code though, nothing functionality wise to comment on -- it looks good..

2022-11-24 15:13 UTC, dadler83 commented on src/main/java/entity_layer/CommonTimeBlock.java
> +        // I'll have to include a check somewhere that doesn't allow start time to be before
nonsensical comment

2022-11-24 15:13 UTC, dadler83 commented on src/main/java/entity_layer/TimeBlock.java
>      int hashCode();
I don't think you need hashCode here because it is overridden from the object class

2022-11-24 15:14 UTC, dadler83 commented on src/main/java/entity_layer/CommonTimeBlock.java
> +        // I'll have to include a check somewhere that doesn't allow start time to be before
If you are going to implement the check do so, if not, let a higher level object implement it

2022-11-25 14:41 UTC, dadler83 approved these changes
These entities look good for now; we'll start using them for the use cases, and clean up code as needed.

2022-11-25 15:22 UTC, Amir1441 approved these changes
The methods look more and more complete now. Each one is more tuned into the specific role it has to play in the entirety of the project. Looks good. With this, the Time Block usecases can now run

2022-11-25 17:28 UTC, Eggathin approved these changes

2022-11-25 17:33 UTC, merged